//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintsSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string TicketType { get; set; }
        public int StudentId { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }
        public string ActionComments { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
